using Microsoft.CodeAnalysis;

namespace PlainlyIpc.SourceGenerator;

[Generator]
public class ProxyAttributeCreator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var source = """
                // <auto-generated/>
                using System;

                namespace PlainlyIpc.SourceGenerator
                {
                    /// <summary>
                    /// Attribute for automatic generation of proxy classes.
                    /// </summary>
                    [AttributeUsage(AttributeTargets.Interface|AttributeTargets.Class)]
                    public sealed class GenerateProxyAttribute : Attribute
                    {
                    }
                }
                """;
        context.AddSource($"{"GenerateProxyAttribute"}.g.cs", source);
    }

}

